version: '3.4'

services:
  ruby_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/ruby_api
    environment:
      RAILS_ENV: development
      DATABASE_URL: sqlite3:/ruby_api/storage/development.sqlite3
